const languages = [
  { langCode: "aa", emoji: "\ud83c\uddea\ud83c\uddf7", countryCode: "er" },
  { langCode: "af", emoji: "\ud83c\uddff\ud83c\uddf7", countryCode: "za" },
  { langCode: "ak", emoji: "\ud83c\uddec\ud83c\udded", countryCode: "gh" },
  { langCode: "tw", emoji: "\ud83c\uddec\ud83c\udded", countryCode: "gh" },
  { langCode: "sq", emoji: "\ud83c\udde6\ud83c\udded", countryCode: "al" },
  { langCode: "am", emoji: "\ud83c\uddea\ud83c\uddf9", countryCode: "et" },
  { langCode: "ar", emoji: "\ud83c\uddef\ud83c\uddf4", countryCode: "jo" },
  { langCode: "hy", emoji: "\ud83c\udde6\ud83c\udded", countryCode: "am" },
  { langCode: "as", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "ae", emoji: "\ud83c\uddee\ud83c\uddf7", countryCode: "ir" },
  { langCode: "az", emoji: "\ud83c\udde6\ud83c\uddff", countryCode: "az" },
  { langCode: "bm", emoji: "\ud83c\uddf2\ud83c\uddf1", countryCode: "ml" },
  { langCode: "be", emoji: "\ud83c\udde7\ud83c\uddfe", countryCode: "by" },
  { langCode: "bn", emoji: "\ud83c\udde7\ud83c\uddf0", countryCode: "bn" },
  { langCode: "bh", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "bi", emoji: "\ud83c\uddfb\ud83c\uddfa", countryCode: "vu" },
  { langCode: "bs", emoji: "\ud83c\udde7\ud83c\uddf7", countryCode: "ba" },
  { langCode: "bg", emoji: "\ud83c\udde7\ud83c\uddff", countryCode: "bg" },
  { langCode: "my", emoji: "\ud83c\uddf2\ud83c\uddf2", countryCode: "mm" },
  { langCode: "ch", emoji: "\ud83c\uddec\ud83c\uddfa", countryCode: "gu" },
  { langCode: "ny", emoji: "\ud83c\uddf2\ud83c\uddfc", countryCode: "mw" },
  { langCode: "zh", emoji: "\ud83c\udde8\ud83c\uddf3", countryCode: "cn" },
  { langCode: "hr", emoji: "\ud83c\udded\ud83c\uddf7", countryCode: "hr" },
  { langCode: "cs", emoji: "\ud83c\udde8\ud83c\uddff", countryCode: "cz" },
  { langCode: "da", emoji: "\ud83c\udde9\ud83c\uddfc", countryCode: "dk" },
  { langCode: "dv", emoji: "\ud83c\uddf2\ud83c\uddfb", countryCode: "mv" },
  { langCode: "nl", emoji: "\ud83c\uddf3\ud83c\uddf1", countryCode: "nl" },
  { langCode: "dz", emoji: "\ud83c\udde7\ud83c\uddf9", countryCode: "bt" },
  { langCode: "en", emoji: "\ud83c\uddfa\ud83c\uddf8", countryCode: "us" },
  { langCode: "et", emoji: "\ud83c\uddea\ud83c\uddea", countryCode: "ee" },
  { langCode: "ee", emoji: "\ud83c\uddec\ud83c\udded", countryCode: "gh" },
  { langCode: "fo", emoji: "\ud83c\uddeb\ud83c\uddf4", countryCode: "fo" },
  { langCode: "fj", emoji: "\ud83c\uddeb\ud83c\udded", countryCode: "fj" },
  { langCode: "fi", emoji: "\ud83c\uddeb\ud83c\uddf2", countryCode: "fi" },
  { langCode: "fr", emoji: "\ud83c\uddeb\ud83c\uddf7", countryCode: "fr" },
  { langCode: "ff", emoji: "\ud83c\uddff\ud83c\uddf8", countryCode: "za" },
  { langCode: "ka", emoji: "\ud83c\uddec\ud83c\uddea", countryCode: "ge" },
  { langCode: "de", emoji: "\ud83c\udde9\ud83c\uddea", countryCode: "de" },
  { langCode: "el", emoji: "\ud83c\uddec\ud83c\uddf0", countryCode: "gr" },
  { langCode: "kl", emoji: "\ud83c\uddec\ud83c\uddf0", countryCode: "dk" },
  { langCode: "gn", emoji: "\ud83c\uddf5\ud83c\uddfe", countryCode: "py" },
  { langCode: "gu", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "ht", emoji: "\ud83c\udded\ud83c\uddf9", countryCode: "ht" },
  { langCode: "ha", emoji: "\ud83c\uddf3\ud83c\uddec", countryCode: "ng" },
  { langCode: "he", emoji: "\ud83c\uddee\ud83c\uddf1", countryCode: "il" },
  { langCode: "hi", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "ho", emoji: "\ud83c\uddf5\ud83c\uddec", countryCode: "pg" },
  { langCode: "hu", emoji: "\ud83c\udded\ud83c\uddfa", countryCode: "hu" },
  { langCode: "is", emoji: "\ud83c\uddee\ud83c\uddf8", countryCode: "is" },
  { langCode: "ig", emoji: "\ud83c\uddf3\ud83c\uddec", countryCode: "ng" },
  { langCode: "id", emoji: "\ud83c\uddee\ud83c\udde9", countryCode: "id" },
  { langCode: "ga", emoji: "\ud83c\uddee\ud83c\uddea", countryCode: "ie" },
  { langCode: "it", emoji: "\ud83c\uddee\ud83c\uddf9", countryCode: "it" },
  { langCode: "ja", emoji: "\ud83c\uddef\ud83c\uddf5", countryCode: "ja" },
  { langCode: "jv", emoji: "\ud83c\uddee\ud83c\udde9", countryCode: "id" },
  { langCode: "kn", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "ks", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "kk", emoji: "\ud83c\uddf0\ud83c\uddff", countryCode: "kz" },
  { langCode: "km", emoji: "\ud83c\uddf0\ud83c\udded", countryCode: "kh" },
  { langCode: "rw", emoji: "\ud83c\uddf7\ud83c\uddfc", countryCode: "rw" },
  { langCode: "kg", emoji: "\ud83c\udde8\ud83c\uddf9", countryCode: "cd" },
  { langCode: "ko", emoji: "\ud83c\uddf0\ud83c\uddf7", countryCode: "kr" },
  { langCode: "kj", emoji: "\ud83c\udde6\ud83c\uddfc", countryCode: "ao" },
  { langCode: "ky", emoji: "\ud83c\uddf0\ud83c\uddf6", countryCode: "kg" },
  { langCode: "lo", emoji: "\ud83c\udde6\ud83c\uddf6", countryCode: "la" },
  { langCode: "la", emoji: "\ud83c\uddfb\ud83c\uddfe", countryCode: "va" },
  { langCode: "lv", emoji: "\ud83c\uddf1\ud83c\uddfb", countryCode: "lv" },
  { langCode: "ln", emoji: "\ud83c\udde8\ud83c\uddf9", countryCode: "cd" },
  { langCode: "lg", emoji: "\ud83c\uddfa\ud83c\uddfc", countryCode: "ug" },
  { langCode: "lb", emoji: "\ud83c\uddf1\ud83c\uddfa", countryCode: "lu" },
  { langCode: "mk", emoji: "\ud83c\uddf2\ud83c\uddf0", countryCode: "mk" },
  { langCode: "mg", emoji: "\ud83c\uddf2\ud83c\uddec", countryCode: "mg" },
  { langCode: "ms", emoji: "\ud83c\uddf2\ud83c\uddf8", countryCode: "my" },
  { langCode: "ml", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "mt", emoji: "\ud83c\uddf2\ud83c\uddf9", countryCode: "mt" },
  { langCode: "gv", emoji: "\ud83c\uddfd", countryCode: "gb" },
  { langCode: "mi", emoji: "\ud83c\uddf3\ud83c\uddf8", countryCode: "nz" },
  { langCode: "mr", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "mh", emoji: "\ud83c\uddf2\ud83c\udded", countryCode: "mh" },
  { langCode: "mn", emoji: "\ud83c\uddf2\ud83c\uddf3", countryCode: "mn" },
  { langCode: "me", emoji: "\ud83c\uddf2\ud83c\uddea", countryCode: "me" },
  { langCode: "na", emoji: "\ud83c\uddf3\ud83c\uddf7", countryCode: "nr" },
  { langCode: "ng", emoji: "\ud83c\uddf3\ud83c\uddfc", countryCode: "na" },
  { langCode: "ne", emoji: "\ud83c\uddf1\ud83c\uddf5", countryCode: "np" },
  { langCode: "se", emoji: "\ud83c\uddf3\ud83c\uddf4", countryCode: "no" },
  { langCode: "no", emoji: "\ud83c\uddf3\ud83c\uddf4", countryCode: "no" },
  { langCode: "or", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "om", emoji: "\ud83c\uddea\ud83c\uddf9", countryCode: "et" },
  { langCode: "pi", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "ps", emoji: "\ud83c\uddf0\ud83c\uddff", countryCode: "af" },
  { langCode: "fa", emoji: "\ud83c\uddee\ud83c\uddf7", countryCode: "ir" },
  { langCode: "pl", emoji: "\ud83c\uddf5\ud83c\uddf1", countryCode: "pl" },
  { langCode: "pt", emoji: "\ud83c\uddf5\ud83c\uddf9", countryCode: "pt" },
  { langCode: "pa", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "qu", emoji: "\ud83c\uddf5\ud83c\uddf7", countryCode: "pe" },
  { langCode: "ro", emoji: "\ud83c\uddf7\ud83c\uddf4", countryCode: "ro" },
  { langCode: "rm", emoji: "\ud83c\uddf8\ud83c\udded", countryCode: "ch" },
  { langCode: "rn", emoji: "\ud83c\uddf7\ud83c\uddfd", countryCode: "bi" },
  { langCode: "ru", emoji: "\ud83c\uddf7\ud83c\uddfa", countryCode: "ru" },
  { langCode: "sg", emoji: "\ud83c\uddf8\ud83c\uddeb", countryCode: "cf" },
  { langCode: "sa", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "gd", emoji: "\ud83c\uddec", countryCode: "gb" },
  { langCode: "sr", emoji: "\ud83c\uddf7\ud83c\uddf8", countryCode: "rs" },
  { langCode: "sh", emoji: "\ud83c\udded\ud83c\uddf7", countryCode: "hr" },
  { langCode: "sn", emoji: "\ud83c\uddf3\ud83c\uddfc", countryCode: "zw" },
  { langCode: "ii", emoji: "\ud83c\udde8\ud83c\uddf3", countryCode: "cn" },
  { langCode: "si", emoji: "\ud83c\uddf1\ud83c\uddf0", countryCode: "lk" },
  { langCode: "sk", emoji: "\ud83c\uddf8\ud83c\uddf0", countryCode: "sk" },
  { langCode: "sl", emoji: "\ud83c\uddf8\ud83c\uddf2", countryCode: "si" },
  { langCode: "so", emoji: "\ud83c\uddf8\ud83c\uddf4", countryCode: "so" },
  { langCode: "nr", emoji: "\ud83c\uddff\ud83c\uddf8", countryCode: "za" },
  { langCode: "st", emoji: "\ud83c\uddff\ud83c\uddf8", countryCode: "za" },
  { langCode: "es", emoji: "\ud83c\uddea\ud83c\uddf7", countryCode: "es" },
  { langCode: "su", emoji: "\ud83c\uddee\ud83c\uddf9", countryCode: "id" },
  { langCode: "sw", emoji: "\ud83c\uddf0\ud83c\uddf0", countryCode: "ke" },
  { langCode: "ss", emoji: "\ud83c\uddf8\ud83c\uddf3", countryCode: "sz" },
  { langCode: "sv", emoji: "\ud83c\uddf8\ud83c\uddf1", countryCode: "se" },
  { langCode: "tl", emoji: "\ud83c\uddf5\ud83c\uddfe", countryCode: "ph" },
  { langCode: "ty", emoji: "\ud83c\uddf5\ud83c\uddeb", countryCode: "pf" },
  { langCode: "tg", emoji: "\ud83c\uddf9\ud83c\uddfe", countryCode: "tj" },
  { langCode: "ta", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "te", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "th", emoji: "\ud83c\uddf9\ud83c\udded", countryCode: "th" },
  { langCode: "bo", emoji: "\ud83c\udde7\ud83c\uddf2", countryCode: "bt" },
  { langCode: "ti", emoji: "\ud83c\uddea\ud83c\uddf7", countryCode: "er" },
  { langCode: "ts", emoji: "\ud83c\uddff\ud83c\uddf7", countryCode: "za" },
  { langCode: "tn", emoji: "\ud83c\uddf7\ud83c\uddf8", countryCode: "bw" },
  { langCode: "tr", emoji: "\ud83c\uddf9\ud83c\uddf7", countryCode: "tr" },
  { langCode: "tk", emoji: "\ud83c\uddf9\ud83c\uddf2", countryCode: "tm" },
  { langCode: "uk", emoji: "\ud83c\uddfa\ud83c\udde6", countryCode: "ua" },
  { langCode: "ur", emoji: "\ud83c\uddee\ud83c\uddf3", countryCode: "in" },
  { langCode: "uz", emoji: "\ud83c\uddfa\ud83c\uddff", countryCode: "uz" },
  { langCode: "ve", emoji: "\ud83c\uddf3\ud83c\uddf8", countryCode: "za" },
  { langCode: "vi", emoji: "\ud83c\uddfa\ud83c\uddf3", countryCode: "vn" },
  { langCode: "wa", emoji: "\ud83c\udde7\ud83c\uddfa", countryCode: "be" },
  { langCode: "cy", emoji: "\ud83c\uddf4", countryCode: "gb" },
  { langCode: "wo", emoji: "\ud83c\udde8\ud83c\uddf3", countryCode: "sn" },
  { langCode: "xh", emoji: "\ud83c\uddff\ud83c\uddf7", countryCode: "za" },
  { langCode: "yi", emoji: "\ud83c\udde9\ud83c\uddf2", countryCode: "il" },
  { langCode: "yo", emoji: "\ud83c\uddf7\ud83c\uddf8", countryCode: "ng" },
  { langCode: "za", emoji: "\ud83c\udde6\ud83c\uddff", countryCode: "za" },
  { langCode: "zu", emoji: "\ud83c\uddff\ud83c\uddf7", countryCode: "za" },
];

console.log(languages);

function getFlag(lan) {
  lan = lan.trim();
  const langEmoji = languages.find(
    (x) => x.langCode == lan || x.countryCode == lan
  );
  if (langEmoji) {
    return langEmoji.emoji;
  } else {
    return lan;
  }
}

export { getFlag };
